version: "3.9"

networks:
    host:
        name: host
        external: true


services:
    spark-master:
        image: elaaf/spark-master
        networks: 
            - host
        ports:
            - "8080:8080"
        expose:
            - "7077"
        extra_hosts:
            - "dg-spark-master:10.51.100.65"
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.hostname==dg-spark-master"
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 1G
    spark-worker:
        image: elaaf/spark-worker
        networks: 
            - host
        ports:
            - "8081:8081"
        extra_hosts:
            - "dg-spark-master:10.51.100.65"
        deploy:
            mode: global
            placement:
                max_replicas_per_node: 1
                constraints:
                    - "node.hostname!=dg-spark-master"
            resources:
                limits:
                    cpus: '3'
                    memory: 8G
                reservations:
                    cpus: '1'
                    memory: 1G
