version: "3.9"

networks:
    spark-net:
        external: true
        driver: overlay
        attachable: true


services:
    spark-master:
        image: elaaf/spark-master
        networks: 
            - spark-net
        ports:
            - "8080:8080"
        expose:
            - "7077"
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.hostname==dg-spark-master"
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 1G
    
    spark-submit:
        image: elaaf/spark-submit
        networks: 
            - spark-net
        entrypoint: tail -f /dev/null
        volumes:
            - $PWD:/spocker
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.hostname==dg-spark-master"
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 1G
    
    spark-worker:
        image: elaaf/spark-worker
        networks: 
            - spark-net
        ports:
        - "8081:8081"
        deploy:
            mode: replicated
            replicas: 4
            placement:
                max_replicas_per_node: 2
                constraints:
                    - "node.hostname!=dg-spark-master"
            resources:
                limits:
                    cpus: '3'
                    memory: 8G
                reservations:
                    cpus: '1'
                    memory: 1G
