version: "3.9"

networks:
    host:
        name: host
        external: true
        attachable: true


services:
    spark-master:
        image: elaaf/spark-master
        hostname: 10.51.100.65
        networks:
            - host
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.hostname==dg-spark-master"
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 1G

    spark-worker:
        image: elaaf/spark-worker
        networks:
            - host
        environment:
             - SPARK_MASTER_URL=spark://10.51.100.65:7077
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.hostname!=dg-spark-master"
            resources:
                limits:
                    cpus: '3'
                    memory: 8G
                reservations:
                    cpus: '1'
                    memory: 1G
