version: "3.9"

services:
    spark-master:
        image: elaaf/spark-master
        ports:
            - "8080:8080"
        expose:
            - "7077"
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.hostname==dg-spark-master"
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 1G
    
    spark-submit:
        image: elaaf/spark-submit
        entrypoint: tail -f /dev/null
        volumes:
            - $PWD:/spocker
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.hostname==dg-spark-master"
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 1G
    
    spark-worker:
        image: elaaf/spark-worker
        ports:
        - "8081:8081"
        deploy:
            mode: replicated
            replicas: 4
            placement:
                max_replicas_per_node: 2
                constraints:
                    - "node.hostname!=dg-spark-master"
            resources:
                limits:
                    cpus: '3'
                    memory: 8G
                reservations:
                    cpus: '1'
                    memory: 1G
networks:
  spark-net:
    driver: overlay
    attachable: true