version: "3.9"

networks:
    host:
        name: host
        external: true
        attachable: true


services:
    spark-master:
        image: elaaf/spark-master
        hostname: ${SPARK_MASTER_IP}
        networks:
            - host
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.role==manager"
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 2G

    spark-worker:
        image: elaaf/spark-worker
        networks:
            - host
        environment:
             - SPARK_WORKER_CPU=1
             - SPARK_WORKER_MEMORY=2G
             - SPARK_MASTER_URL=spark://${SPARK_MASTER_IP}:7077
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.role==worker"
            resources:
                limits:
                    cpus: '2'
                    memory: 8G
                reservations:
                    cpus: '1'
                    memory: 2G
