version: "3.2"

services:
    spark-master:
        image: elaaf/spark-master
        container_name: "spark-master"  
        build: .
        ports:
            - "8080:8080"
        expose:
            - "7077"
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.hostname==dg-spark-master"
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 1G

    spark-submit:
        image: elaaf/spark-submit
        container_name: "spark-submit"
        build: .
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.hostname==dg-spark-master"
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 1G

    spark-worker:
        image: elaaf/spark-worker
        container_name: "spark-worker"
        build: .
        ports:
        - "8081:8081"
        deploy:
            mode: replicated
            replicas: 2
            placement:
                constraints:
                    - "node.hostname==dg-spark-worker"
                    - max_replicas_per_node: 2
            resources:
                limits:
                    cpus: '3'
                    memory: 8G
                reservations:
                    cpus: '1'
                    memory: 1G


    # spark-worker-1:
    #     image: elaaf/spark-worker
    #     container_name: "spark-worker-1"
    #     build:
    #         context: .
    #         network: spark-net
    #     ports:
    #     - "8081:8081"
    #     deploy:
    #         mode: global
    #         placement:
    #             constraints:
    #                 - node.hostname == *worker
    
