version: "3.9"

networks:
    spark-net:
        name: spark-net
        driver: overlay
        external: false
        attachable: true


services:
    spark-master:
        image: elaaf/spark-master
        hostname: spark-master
        networks:
            - spark-net
        ports:
            - "8080:8080"
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.role==manager"
            resources:
                limits:
                    cpus: '4'
                    memory: 8G
                reservations:
                    cpus: '1'
                    memory: 2G

    spark-worker:
        image: elaaf/spark-worker
        networks:
            - spark-net
        ports:
            - "8081:8081"
        environment:
             - SPARK_WORKER_CPU=8
             - SPARK_WORKER_MEMORY=30G
             - SPARK_MASTER_URL=spark://spark-master:7077
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.role==worker"
            resources:
                limits:
                    cpus: '8'
                    memory: 30G
                reservations:
                    cpus: '1'
                    memory: 2G
