# >>>>>>>>>>>>>>>>>>>> DO NOT USE: INCOMPLETE <<<<<<<<<<<<<<<<<<<<

FROM elaaf/alpine:latest
LABEL maintainer="Elaaf Shuja <elaaf.shuja@gmail.com>"

# Install hadoop

# Final Stuff
ENTRYPOINT ["/bin/bash"]

# >>>>>>>>>>>>>>>>>>>> DO NOT USE: INCOMPLETE <<<<<<<<<<<<<<<<<<<<