version: "beta"

services:
    master:
        image: elaaf/spark-master
        container_name: "spark-master"  
        build: .
        ports:
            - "8080:8080"
        expose:
            - "7077"

    worker1:
        image: elaaf/spark-worker
        container_name: "spark-worker-1"
        build: .
        ports:
        - "8081:8081"
    
    worker2:
        image: elaaf/spark-worker
        container_name: "spark-worker-2"
        build: .
        ports:
        - "8082:8081"