version: "3.7"

services:
    spark-master:
        image: elaaf/spark-master:latest
        networks:
        - spark-net
        ports:
            - "8080:8080"
        expose:
            - "7077"


    spark-worker-1:
        image: elaaf/spark-worker:latest
        networks:
        - spark-net
        ports:
        - "8081:8081"


    spark-worker-2:
        image: elaaf/spark-worker:latest
        networks:
        - spark-net
        ports:
        - "8082:8081"


networks:
        spark-net:
                name: spark-net
                external: false
                attachable: true
